[profile.default]
src = "contract"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [
    { access = "read", path = "./images/" },
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./" }
]
solc_version = "0.8.20"

remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    '@chainlink/contracts/=lib/chainlink/contracts',
    '@chainlink/contracts-ccip/=lib/ccip/contracts'
]

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mumbai = { key = "${POLYGONSCAN_API_KEY}" }
baseSepolia = { key = "{BASESCAN_API_KEY}"}
arbitrumSepolia = { key = "{ARBITRUMSCAN_API_KEY}"}
baseMainnet = { key = "{BASESCAN_API_KEY}"}

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"
fuji = "${FUJI_RPC_URL}"
baseSepolia = "${BASE_SEPOLIA_RPC_URL}"
arbitrumSepolia = "${ARBITRUM_RPC_URL}"
baseMainnet = "${BASE_MAINNET_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
